USE Test8_TruyVanCoBan
GO

SELECT MAGV FROM dbo.GIAOVIEN
WHERE LUONG >=2500

SELECT MAGV FROM dbo.NGUOITHAN
WHERE PHAI = N'Nữ'

-- Kết hợp 2 cột và loại bỏ giá trị trùng
SELECT MAGV FROM dbo.GIAOVIEN
WHERE LUONG >=2500
UNION
SELECT MAGV FROM dbo.NGUOITHAN
WHERE PHAI = N'Nữ'