-- HAVING là WHERE của GROUP BY

-- Xuất ra số lượng giáo viên trong từng bộ môn mà số giáo viên > 1
SELECT TENBM, COUNT(*) AS N'Số lượng giáo viên' FROM dbo.BOMON
JOIN dbo.GIAOVIEN ON GIAOVIEN.MABM = BOMON.MABM
GROUP BY TENBM HAVING COUNT(MAGV)>1

-- Xuất ra mức lương, tổng tuổi của các giáo viên có người thân nhận mức lương đó
-- điều kiện là tuổi của các giáo viên đó phải lớn hơn tuổi trung bình của các giáo viên đó
SELECT LUONG, SUM(YEAR(GETDATE()) - YEAR(GIAOVIEN.NGSINH)) FROM dbo.GIAOVIEN
JOIN dbo.NGUOITHAN ON NGUOITHAN.MAGV = GIAOVIEN.MAGV
GROUP BY LUONG, GIAOVIEN.NGSINH
HAVING (YEAR(GETDATE()) - YEAR(GIAOVIEN.NGSINH)) > 
(
	SELECT AVG(YEAR(GETDATE())-YEAR(GIAOVIEN.NGSINH)) FROM dbo.GIAOVIEN
	JOIN dbo.NGUOITHAN ON NGUOITHAN.MAGV = GIAOVIEN.MAGV
)

SELECT YEAR(GETDATE()) - AVG(YEAR(GIAOVIEN.NGSINH)) FROM dbo.GIAOVIEN
JOIN dbo.NGUOITHAN ON NGUOITHAN.MAGV = GIAOVIEN.MAGV

SELECT GV.*, YEAR(GETDATE()) - YEAR(GV.NGSINH) FROM dbo.GIAOVIEN AS GV
JOIN dbo.NGUOITHAN ON NGUOITHAN.MAGV = GV.MAGV
